from typing import Any

from typing_extensions import TypeAlias

LuaArg: TypeAlias = str | int | float

class ScriptingCommandsMixin:
    async def eval(
        self, script: str, keys: list[LuaArg] = ..., args: list[LuaArg] = ...
    ) -> Any: ...
    async def evalsha(
        self, sha: str, keys: list[LuaArg] = ..., args: list[LuaArg] = ...
    ) -> Any: ...
    async def script_load(self, script: str) -> str: ...
