from .commands.scripting import ScriptingCommandsMixin
from .commands.generic import GenericCommandsMixin

class Redis(GenericCommandsMixin, ScriptingCommandsMixin):
    def close(self) -> None: ...
    async def wait_closed(self) -> None: ...

async def create_redis(address: str) -> Redis: ...
